### ISSUE TITLE
We love marvelco

### ISSUE THREAD

**Issue by optixyt0** [MarvelcoOGFN/Ero-backend#1]
I love marvelco

**Comment by MarvelcoOGFN** [comment]
Umm bro it says in the read me base lawin also eon gs has alot of issue bro litterly fixed all of them also in the read me it says credits to eon :skull:

**Comment by MarvelcoOGFN** [comment]
Umm bro it says in the read me base lawin also eon gs has alot of issue bro litterly fixed all of them also in the read me it says credits to eon :skull:

**Comment by MarvelcoOGFN** [comment]
Just saying bro what ever you say no one will believe you
